### ISSUE TITLE
Update @sentry/cli to v2.x

### ISSUE THREAD

**Issue by scefali** [getsentry/action-release#119] opened 2022-12-08 00:19 UTC
We should upgrade the `@sentry/cli` package to the latest version as there are surely some changes we want in this package

**Comment by brianthi** [comment] 2022-12-12 18:28
Closing as this is a duplicate of https://github.com/getsentry/action-release/issues/101#issue-1321396593

**Closed by brianthi** 2022-12-12 18:28 UTC
