### ISSUE TITLE
Run linting and tests as part of the CI

### ISSUE THREAD

**Issue by armenzg** [getsentry/action-release#147] opened 2023-04-20 14:01 UTC
I got the tests running locally but they fail remotely:
https://github.com/getsentry/action-release/actions/runs/4755157537/jobs/8448932238?pr=146

```
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at hashOf (/home/runner/work/action-release/action-release/node_modules/@zeit/ncc/dist/ncc/index.js.cache.js:3:58216)
    at module.exports (/home/runner/work/action-release/action-release/node_modules/@zeit/ncc/dist/ncc/index.js.cache.js:3:60642)
    at runCmd (/home/runner/work/action-release/action-release/node_modules/@zeit/ncc/dist/ncc/cli.js.cache.js:1:47355)
    at 819 (/home/runner/work/action-release/action-release/node_modules/@zeit/ncc/dist/ncc/cli.js.cache.js:1:44227)
    at __webpack_require__ (/home/runner/work/action-release/action-release/node_modules/@zeit/ncc/dist/ncc/cli.js.cache.js:1:169)
    at startup (/home/runner/work/action-release/action-release/node_modules/@zeit/ncc/dist/ncc/cli.js.cache.js:1:339)
    at module.exports.8 (/home/runner/work/action-release/action-release/node_modules/@zeit/ncc/dist/ncc/cli.js.cache.js:1:371)
    at /home/runner/work/action-release/action-release/node_modules/@zeit/ncc/dist/ncc/cli.js.cache.js:1:381 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

**Comment by smeubank** [comment] 2024-12-10 15:15
https://github.com/getsentry/action-release/issues/85

duplicate of this issue

**Closed** 2024-12-10 15:18 UTC
