### ISSUE TITLE
Incorrect example of how to set the `version` parameter

### ISSUE THREAD

**Issue by AJenbo** [getsentry/action-release#79] opened 2022-02-18 11:47 UTC
### Environment

https://github.com/marketplace/actions/sentry-release#examples

The given example is wrong:
```
- uses: getsentry/action-release@v1
  with:
    environment: 'production'
    version: 'v1.0.1'
```

### Steps to Reproduce

1. Use the given example

### Expected Result

Version is set to 'v1.0.1'

### Actual Result

`Warning: Unexpected input(s) 'version', valid inputs are ['entryPoint', 'args', 'environment', 'sourcemaps', 'finalize', 'started_at']`

**Comment by xavierchow** [comment] 2022-05-07 07:40
@AJenbo I guess you just need to bump up to 1.1.6
```
      - name: Sentry Release
        uses: getsentry/action-release@v1.1.6

```

**Comment by smeubank** [comment] 2024-12-11 10:15
https://github.com/getsentry/action-release/issues/49

appears to be a duplicate of this issue. Closing and linking

**Closed by smeubank** 2024-12-11 10:15 UTC
