### ISSUE TITLE
Warning: "Unexpected input(s) 'dist'"

### ISSUE THREAD

**Issue by decline** [getsentry/action-release#174] opened 2023-11-15 14:23 UTC
# Github Sentry Action Release Bug Report

## Environment
- runs-on: ubuntu-latest (GitHub runner)
- uses: getsentry/action-release@v1

## Steps to Reproduce
I am using the `dist` input like this:

```yml
with:
  dist: ${{ github.run_number }}
```

## Expected Result
It should set the run number as the dist without any problems.

## Actual Result
It will correctly use the run number as the dist (I can see it correctly in Sentry). But it will output the following warning:

```
Unexpected input(s) 'dist', valid inputs are ['entryPoint', 'args', 'environment', 'sourcemaps', 'finalize', 'ignore_missing', 'ignore_empty', 'started_at', 'version', 'version_prefix', 'set_commits', 'projects', 'url_prefix', 'strip_common_prefix', 'working_directory']
```

See screenshot too:
<img width="685" alt="Screenshot 2023-11-15 at 15 21 26" src="https://github.com/getsentry/action-release/assets/5609744/23bbcd6d-ce88-4cba-9fc0-0a03f1bb1642">

**Comment by franklinrabay** [comment] 2024-04-04 12:31
I also stumbled on it, and i found here it was already reported, any updates? :thinking:

**Comment by smeubank** [comment] 2024-12-10 15:59
closing issue as a duplicate of this https://github.com/getsentry/action-release/issues/49

**Closed by smeubank** 2024-12-10 15:59 UTC
Labels: bug
